######################################################################
# Automatically generated by qmake (3.0) ?? ???. 9 14:01:03 2018
######################################################################

TEMPLATE = app
TARGET = ftp
INCLUDEPATH += .
QT +=  core network 

# Input
HEADERS += ftp.h
SOURCES += ftp.cpp
